# Generated by Django 4.2.13 on 2024-05-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('place', models.CharField(max_length=200)),
                ('mob_no', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=5000)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('school_attended', models.CharField(max_length=200)),
                ('academic_qualifications', models.CharField(max_length=5000)),
                ('certifications', models.CharField(max_length=5000)),
                ('work_history', models.CharField(max_length=5000)),
            ],
        ),
    ]
