# Generated by Django 4.2.13 on 2024-05-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='academic_qualifications',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='certifications',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='skills',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='work_history',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
